export const featureRoleMap = [
    {
        roleName: "CHECKER",
        featureList: [
            "home",
            "mobile-recharge",
            "Example 2",
            "Example 3",
            "transaction",
            "approve-mfs-ledger-transaction",
            "account",
            "account-statement",
            "account-balance",
            "account-detail",
            "account-create",
            "ledger",
            "txnType",
            "txnType-free",
            "txnType-type",
            "report",
            "income-statement",
            "balance-sheet",
            "registration",
            "registration-list",
            "approve-registration",
            "credit",
            "loan-product-list",
            "loan-applications",
            "loans",
        ]
    },
    {
        roleName: "MAKER",
        featureList: [
            "home",
            "mobile-recharge",
            "Example 1",
            "Example 2",
            "Example 3",
            "Example 5",
            "transaction",
            "create-mfs-ledger-transaction",
            "status-mfs-ledger-transaction",
            "account",
            "account-statement",
            "account-balance",
            "account-detail",
            "account-create",
            "ledger",
            "txnType",
            "txnType-free",
            "txnType-type",
            "report",
            "income-statement",
            "balance-sheet",
            "registration",
            "registration-list",
            "registration-create",
            "status-registration",
            "create-registration",
            "bulk-registration",
            "credit",
            "loan-product-list",
            "create-loan-product",
            "loan-applications",
            "create-loan-applications",
            "loans"
        ]
    },
    {
        roleName: "USER",
        featureList: [
            "home",
            "mobile-recharge",
            "add-money",
            "pay-bill",
            "credit",
            "bank-transfer",
            "payment",
            "send-money",
            "wealth",
            "logout",
            "Example 1",
            "Example 2",
            "Example 3",
            "Example 5",
            "transaction",
            "create-mfs-ledger-transaction",
            "status-mfs-ledger-transaction",
            "account",
            "account-statement",
            "account-balance",
            "account-detail",
            "account-create",
            "ledger",
            "txnType",
            "txnType-free",
            "txnType-type",
            "report",
            "income-statement",
            "balance-sheet",
            "registration",
            "registration-list",
            "registration-create",
            "status-registration",
            "create-registration",
            "bulk-registration",
            "credit",
            "loan-product-list",
            "create-loan-product",
            "loan-applications",
            "create-loan-applications",
            "loans"
        ]
    }
]
